name: release

env:
  java_version: 17

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.java_version }} for x64
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java_version }}
          distribution: "temurin"
          architecture: x64
      
      - name: Build and upload artifact and release
        run: ./gradlew :plugins:nf-kafka:upload
